#
# Module manifest for module 'PSMPyTools'
#
# Generated by: Frank Lindenblatt (Flittermelint)
#
# Generated on: 2025-05-21
#
@{
    RootModule        = 'PSMPyTools.psm1'

    ModuleVersion     = '0.0.1'

    GUID              = '8222f67f-a439-494c-bb77-3477278c859a'

    Author            = 'Frank Lindenblatt (Flittermelint)'

    Copyright         = 'Copyright (c) 2025 Frank Lindenblatt (Flittermelint), licensed under the MIT License.'

    Description       = 'Install and manage MicroPython on ESP32 chips'

    PowerShellVersion = '5.1'

    PrivateData = @{

        PSData = @{

            Tags       = @('powershell', 'micropython', 'python', 'iot', 'esp32')

            ProjectUri = 'https://github.com/Flittermelint/PSMPyTools'

            LicenseUri = 'https://github.com/Flittermelint/PSMPyTools/raw/main/LICENSE'

            IconUri    = 'https://github.com/Flittermelint/PSMPyTools/raw/main/Images/PSMPyTools.Logo.png'
        }
    }
}
